
namespace BillingApplication.Core.Queries
{
    public static class PumpQueries
    {
        public const string GetPumpForCashier = 
        @"SELECT * 
          FROM PUMPS P
          INNER JOIN CASHIERS C ON P.CASHIER = C.CASHIERS_ID
          WHERE CASHIER = @CASHIERID AND ISACCOUNTABLE = 1 ORDER BY [ORDER]";

        public const string GetPumpShiftDetailsForCashier =
        @"SELECT C.NAME AS CASHIERNAME, P.PUMPS_ID, P.NAME, P.RATE, P.INITIALREADING, P.CURRENTREADING, P.CASHIER AS CURRENTCASHIER, P.LASTUPDATED, 
                 PSD.PUMPSHIFTDETAILS_ID, PSD.STARTTIME, PSD.ENDTIME, PSD.OPENINGREADING, PSD.CLOSINGREADING, PSD.TESTING, PSD.SALES, PSD.RATE, PSD.AMOUNT, PSD.CASHIER
          FROM PUMPSHIFTDETAILS PSD
          INNER JOIN PUMPS P ON P.PUMPS_ID = PSD.PUMPS_ID
          INNER JOIN CASHIERS C ON PSD.CASHIER = C.CASHIERS_ID
          WHERE PSD.CASHIER = @CASHIERID AND PSD.SHIFTCLOSECOMPLETE = 0 ORDER BY P.[ORDER]";

        public const string UpdateShiftCloseComplete =
            @" UPDATE PUMPSHIFTDETAILS SET SHIFTCLOSECOMPLETE = 1
               WHERE CASHIER = @CASHIERID AND SHIFTCLOSECOMPLETE = 0";

        public const string AddProducts =
            @" UPDATE PUMPS SET CURRENTREADING = (CURRENTREADING + @COUNT) WHERE PUMPS_ID = @PRODUCTID";
    }
}
